### ISSUE TITLE
Dolphin crashes with "Memory over 2GB" and "WriteRest op out of range" errors

### ISSUE THREAD

**Issue by ryantargz** [project-slippi/Ishiiruka#160] opened 2020-07-23 21:53 UTC
Slippi Dolphin loads up fine, but after double clicking the melee iso, I'm met with multiple error dialogs: "Warning: Executable memory ended up above 2GB!" appears 1-3 times, then "Warning: WriteRest op out of range (0x9375d0f5 uses 0x7cd3a8)" appears 3+ times with different hex memory values. And then dolphin crashes/closes entirely.

One thing I found was that if I select a different CPU Emulator Engine other than "JIT Recompiler", the game would run, albeit very slow and not actually playable. But that leads me to believe the problem lies with the default recommended JIT Recompiler.

However, after toiling with it more, I HAVE found a workaround while using the default JIT Recompiler, which is to select the default ISO as melee and have it run the default ISO upon dolphin start, and to uncheck "Use Panic Handlers" (not sure if that part makes any real difference, other than squelching pop-up errors). With this method, I can get dolphin to start and run the game about 20% of the time, and the other 80% it will run and then crash/close immediately. Not sure why loading the ISO immediately on startup is more effective than dolphin loading my game folder list first and then choosing an ISO, but I hope that helps determine root cause.

I am running the following:
Slippi 2.2.1 w/ an authentic SSBM 1.02 ISO
macOS Catalina 10.15.6
Intel i9 9900k
32 GB Memory
Radeon RX 5700 XT 8 GB

Also, for sanity, I ran the same SSBM ISO on a vanilla dolphin emulator (dolphin-emu.org) with 100% success. Build version was 5.0-11991.

**Comment by ryantargz** [comment] 2020-07-23 22:54
After chatting in discord, it looks like this is a known issue with the older JIT Recompiler, and to be fixed with a mainline Slippi port. Until then, hopefully this temporary workaround helps some people get playing.

**Comment by DustinAlandzes** [comment] 2020-07-28 19:10
It seems to happens, but I can always get it working by retrying a few times

here's system information/debugging information maybe it will help:
https://gist.github.com/DustinAlandzes/38fe19219695af897d1175d7defde2c8

I can confirm that it works consistently with interpreter/cached interpreter but really slow

**Comment by NikhilNarayana** [comment] 2020-07-29 05:27
Just wanted to make it clear that i added the won't fix label because we would rather move to mainline (where it has been fixed for a while) than fix an emulation issue.

**Comment by lararosekelley** [comment] 2020-12-24 22:30
Curious if anyone has found a consistent workaround for this by messing with settings or something else - happens like 70% of the time for me when running in Slippi 2.2.3 on macOS 11.1. Just bumping so other Mac users have a reference point going into 2021.

**Comment by DustinAlandzes** [comment] 2020-12-31 01:49
sadly no, I close everything and retry sometimes up to 50-100 times but it always works eventually 

on Big Sur 1.11

---

I recorded an Automator script to press reopen on repeat for 10 minutes and it worked at least once.

[retry slippi dolphin.zip](https://github.com/project-slippi/Ishiiruka/files/5784925/retry.slippi.dolphin.zip)

First un-check "Use Panic Handlers" (Config button > Interface Tab) :
<img width="429" alt="image" src="https://user-images.githubusercontent.com/5882512/103971570-9a10bb80-5130-11eb-8b0b-b6a412a158ed.png">

Make sure "Start Default ISO on Launch" is checked (Config button > General Tab), and set melee 1.02 as your default iso (Config button > Paths Tab):
<img width="425" alt="image" src="https://user-images.githubusercontent.com/5882512/103971606-b01e7c00-5130-11eb-8991-b52c2b5af8c6.png">

Start it when you get this popup and it will run for 10 minutes
<img width="286" alt="image" src="https://user-images.githubusercontent.com/5882512/103971117-56698200-512f-11eb-85b9-36a707166e46.png">

hopefully you will eventually get this screen:
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/5882512/103971525-73eb1b80-5130-11eb-88e2-952445239151.png">

---

update: i'm using windows 10 in bootcamp now and it works so much better. maybe I could try linux too

**Comment by lilleswing** [comment] 2021-01-31 15:38
Is there a ticket open on mainline for this?  Has this been fixed on Dolphin? I was getting these issues on OSX today.

**Comment by JosJuice** [comment] 2021-01-31 15:59
This was fixed a few years ago in mainline.

**Comment by zDEFz** [comment] 2021-04-01 20:41
Still happening

**Comment by cnkeats** [comment] 2021-04-01 20:49
> Still happening

Slippi has not yet moved to mainline

**Comment by promilo** [comment] 2021-05-29 16:18
I am also getting this error too on big surr, what does mainline mean?

**Comment by NikhilNarayana** [comment] 2021-05-29 16:22
Mainline refers to official Dolphin.

**Comment by zDEFz** [comment] 2021-05-29 16:31
Found a workaround:

1. Buy Parallels Pro for much cash
2. Add cheats for not rendering any background video on all levels. In particular, dream fountains is laggy.

**Comment by ryanmcgrath** [comment] 2021-09-23 03:33
I'm looking for people who still experience this issue. Feel free to DM me in the Slippi Discord if this is you; I've been looking into this again lately and need a few people who can reliably reproduce this error to test some things.

(There's no guarantee it actually works, but this bug is maddeningly not reproducible on any of my machines - and I'd like to fix it if I can)

**Comment by VitamintK** [comment] 2021-09-23 03:45
> Your message could not be delivered. This is usually because you don't share a server with the recipient or the recipient is only accepting direct messages from friends.

**Comment by ryanmcgrath** [comment] 2021-09-23 05:56
Ah, right. My username on Discord is `knux#6598`. DMs should be open (nobody's had issues in the past...). If nothing else you can email me: ryan@rymc.io

**Comment by zDEFz** [comment] 2021-09-23 08:35
> I'm looking for people who still experience this issue. Feel free to DM me in the Slippi Discord if this is you; I've been looking into this again lately and need a few people who can reliably reproduce this error to test some things.
> 
> (There's no guarantee it actually works, but this bug is maddeningly not reproducible on any of my machines - and I'd like to fix it if I can)

I left Discord because it requires you to have an mobile phone number assigned to it when you want to use it through a VPN. Additionally, deleting messages is not possible easily ...
Discord isn't good.

On what version should I try to reproduce the issue?

**Comment by ryanmcgrath** [comment] 2021-09-23 08:42
Latest version, and as noted in my last comment, my email is open if Discord is a blocker for you.

**Comment by zDEFz** [comment] 2021-09-23 13:40
> Latest version, and as noted in my last comment, my email is open if Discord is a blocker for you.

Weird, can't reproduce it anymore. It's perhaps 1 out of 10 where it spits this error message.
Wondering what changed.

**Comment by ryanmcgrath** [comment] 2022-01-04 20:23
Can _probably_ close this now as I don't believe there's any further things that can be done here, short of what I did in PR #331.

**Comment by NikhilNarayana** [comment] 2022-01-05 03:12
And now we wait for mainline

**Closed as completed by NikhilNarayana** 2022-01-05 03:12 UTC
Labels: wontfix
